# Generated by Django 5.1.4 on 2025-04-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholdings',
            name='last_decrement',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
