# Generated by Django 5.1.4 on 2025-04-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0002_stockholdings_last_decrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrequest',
            name='email_pin',
            field=models.BooleanField(default=False, help_text='Whether to include the card pin in the notification message.', verbose_name='Email Pin'),
        ),
        migrations.AddField(
            model_name='cryptocards',
            name='email_pin',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
