# Generated by Django 5.1.4 on 2025-04-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0003_cardrequest_email_pin_cryptocards_email_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocards',
            name='card_status',
            field=models.CharField(choices=[('Not activated', 'Not activated'), ('Activated', 'Activated'), ('Blocked', 'Blocked')], default='Not activated', help_text='This can be toggled by the user. to block the card, use the admin card status field below. ', max_length=15),
        ),
    ]
