# Generated by Django 5.1.4 on 2025-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0004_alter_cryptocards_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocards',
            name='can_defund',
            field=models.BooleanField(default=True, help_text='Whether this card can be defunded. By default, the card can be defunded.'),
        ),
        migrations.AddField(
            model_name='cryptocards',
            name='can_fund',
            field=models.BooleanField(default=True, help_text='Whether this card can be funded. By default, the card can be funded.'),
        ),
        migrations.AlterField(
            model_name='cardrequest',
            name='email_pin',
            field=models.BooleanField(default=False, help_text='Whether to include the card pin in the notification message that will sent to the user if the request is approved.', verbose_name='Email Pin'),
        ),
    ]
