# Generated by Django 5.1.4 on 2025-04-30 22:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0005_cryptocards_can_defund_cryptocards_can_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='referral_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
