# Generated by Django 5.1.4 on 2025-05-01 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0006_alter_referrals_referral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balances',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balances',
            name='deposits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balances',
            name='profits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ReferralCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_credit', models.DecimalField(decimal_places=2, default=0.0, help_text="Amount of referral credits to add to the referrer's account", max_digits=10)),
                ('referred_credit', models.DecimalField(decimal_places=2, default=0.0, help_text="Amount of referral credits to add to the referred's account", max_digits=10)),
                ('credited', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
