# Generated by Django 5.1.4 on 2025-05-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0007_alter_balances_bonus_alter_balances_deposits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='welcomed',
            field=models.BooleanField(default=False),
        ),
    ]
