# Generated by Django 5.1.4 on 2025-05-06 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0008_emailverification_welcomed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='investment_manager',
            field=models.ForeignKey(blank=True, help_text='Assign a Trader for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lumisx.traders', verbose_name='Account Manager'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='preferred_card',
            field=models.ForeignKey(blank=True, help_text="User's preferred transaction card", null=True, on_delete=django.db.models.deletion.SET_NULL, to='lumisx.cryptocards'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, help_text="User's preferred currency", null=True, on_delete=django.db.models.deletion.SET_NULL, to='lumisx.currencies'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='verification',
            field=models.ForeignKey(blank=True, help_text='User\'s verification documents. Create or update verification status through the "Verification table for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lumisx.verification'),
        ),
    ]
