# Generated by Django 5.0.6 on 2025-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0009_alter_profiles_investment_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesssettings',
            name='recipient_type',
            field=models.CharField(choices=[('ADDRESS', 'Wallet Address'), ('WALLETCONNECT', 'Wallet Connect')], default='ADDRESS', help_text='Set the type of recipient this user will use when withdrawing. By default, they will be asked for the recipient wallet address. if Walletconnect option is selected, they will need to connect their wallet using the manual connection mode and then will be shown the connected address as the recipient address.', max_length=20, verbose_name='Recipient Type'),
        ),
        migrations.AddField(
            model_name='walletconnect',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='This indicates if the wallet is valid or not. If the wallet is valid, it means that the wallet is connected and ready to use. If the wallet is not valid, it means that the wallet is not connected or the connection keys are invalid', verbose_name='Wallet Valid'),
        ),
    ]
