# Generated by Django 5.1.4 on 2025-05-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0010_accesssettings_recipient_type_walletconnect_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='losses_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.05, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='accesssettings',
            name='min_gold_purchase',
            field=models.IntegerField(default=5000, help_text='(GBP)', verbose_name='Minimum Gold Purchase'),
        ),
    ]
