# Generated by Django 5.0.6 on 2025-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0011_investments_losses_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict, help_text='This field stores the terms and conditions in a JSON format (inside a curly brace ). The content should be structured as a key-value pair, each containing a title and content. Example: {"title1": "paragraph1", "title2": "content2"} etc. separate each title and content with a comma.')),
            ],
        ),
    ]
