# Generated by Django 5.1.4 on 2025-07-13 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0013_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='losses_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=2.0, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='DemoBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('profits', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemoTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.IntegerField(default=24)),
                ('profit_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('losses_rate', models.DecimalField(blank=True, decimal_places=2, default=2.0, max_digits=5, null=True)),
                ('total_profits_accrued', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hours_remaining', models.IntegerField(blank=True, null=True)),
                ('last_decrement', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reference', models.CharField(default='', max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='awaiting slot entry', max_length=100)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemoTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEMO TRADING', 'Demo Trading'), ('PROFITS', 'Profits'), ('LOSS', 'Loss')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
