# Generated by Django 5.1.4 on 2025-07-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0014_alter_investments_losses_rate_demobalance_demotrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Lumis X', max_length=255)),
                ('app_version', models.CharField(default='1.0.0', max_length=10)),
                ('app_logo', models.ImageField(blank=True, null=True, upload_to='app_logos/')),
                ('support_email', models.EmailField(default='helpdesk247@lumisx.exchange', max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='demotrade',
            name='losses_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=5, null=True),
        ),
    ]
