# Generated by Django 5.1.4 on 2025-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0015_manifest_alter_demotrade_losses_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
