# Generated by Django 5.1.4 on 2025-09-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0016_user_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal', models.DecimalField(blank=True, decimal_places=2, default=150.0, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('card_funding', models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=10, null=True)),
                ('card_offload', models.DecimalField(blank=True, decimal_places=2, default=30.0, max_digits=10, null=True)),
            ],
        ),
    ]
