# Generated by Django 5.1.4 on 2025-09-09 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0017_transactionfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetracker',
            name='last_card_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='balancetracker',
            name='transaction_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lumisx.cryptocards'),
        ),
    ]
