# Generated by Django 5.1.4 on 2025-09-09 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0018_balancetracker_last_card_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetracker',
            name='transaction_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lumisx.cryptocards'),
        ),
    ]
