# Generated by Django 5.1.4 on 2025-09-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0019_alter_balancetracker_transaction_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfees',
            name='card_funding',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.95, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfees',
            name='card_offload',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfees',
            name='withdrawal',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.5, max_digits=10, null=True),
        ),
    ]
