# Generated by Django 5.1.4 on 2025-09-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0021_alter_transactionfees_card_funding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfees',
            name='card_funding',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0095, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfees',
            name='card_offload',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.005, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfees',
            name='withdrawal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.04, max_digits=10, null=True),
        ),
    ]
