# Generated by Django 5.1.4 on 2025-10-27 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0022_alter_transactionfees_card_funding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demobalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='walletaddresses',
            name='label',
            field=models.TextField(blank=True, help_text='example: binance, trust wallet, etc...', null=True),
        ),
    ]
