# Generated by Django 5.1.4 on 2025-11-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0023_alter_demobalance_user_alter_walletaddresses_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='min_required_version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
        migrations.AddField(
            model_name='manifest',
            name='release_notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifest',
            name='update_url',
            field=models.URLField(default='https://lumisx.exchange'),
        ),
    ]
