# Generated by Django 5.1.4 on 2025-11-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0024_manifest_min_required_version_manifest_release_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesssettings',
            name='push_notifications',
            field=models.BooleanField(default=False, help_text='Whether this user can receive push notifications. the user can turn this on or off in their account settings'),
        ),
    ]
