# Generated by Django 5.1.4 on 2026-06-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0025_accesssettings_push_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='date_started',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='update_url',
            field=models.URLField(default='https://lumisx.exchange/'),
        ),
        migrations.AlterField(
            model_name='walletaddresses',
            name='label',
            field=models.TextField(blank=True, help_text='example: binance, trust wallet, etc...(not shown to user)', null=True),
        ),
    ]
