# Generated by Django 5.1.4 on 2026-06-08 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0026_investments_date_started_alter_manifest_update_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='losseshistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
