# Generated by Django 5.1.4 on 2026-06-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisx', '0027_alter_losseshistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='market',
            field=models.CharField(choices=[('NASDAQ', 'NASDAQ (New York)'), ('LSE', 'LSE (London)'), ('NYSE', 'NYSE (New York)')], default='NASDAQ', max_length=10),
        ),
    ]
